### ISSUE TITLE
字符串乱码

### ISSUE THREAD

**Issue by Jasonbourne723** [taosdata/taos-connector-csharp#246]
![image](https://user-images.githubusercontent.com/42246531/225587419-1fcab046-686c-48ea-8c9b-6686fd8f3531.png)

**Comment by Jasonbourne723** [comment]
reader.getstring(1) 得到的字符串 编码错误， 无法正常使用

**Comment by maikebing** [comment]
尝试一下  新代码？

**Comment by maikebing** [comment]
修改的有问题。

**Comment by maikebing** [comment]
已经修复。
