### ISSUE TITLE
DataReaderExtensions.cs当字段值为null时异常

### ISSUE THREAD

**Issue by winnyrain** [taosdata/taos-connector-csharp#262]
其中里面的好几个函数都有这句：
 if (dataReader[i] != DBNull.Value)
但当数据字段为空null时，这个判断不会生效，继续执行下一句Convert.ChangeType会报异常
InvalidCastException: Null object cannot be converted to a value type.

应该改为
 if (dataReader[i] !=null && dataReader[i] != DBNull.Value)

**Comment by maikebing** [comment]
发个修改PR看看？

**Comment by winnyrain** [comment]
已提交PR，刚看到你也好像改了哈~

**Comment by maikebing** [comment]
#265
