### ISSUE TITLE
IoTSharp.Data.Taos.Protocols.TaosNative 类的 Open 方法中存在线程安全问题

### ISSUE THREAD

**Issue by lves2014** [taosdata/taos-connector-csharp#272]
高并发时执行报错，g_pool 存在线程安全问题。

private static readonly Dictionary<string, ConcurrentTaosQueue> g_pool = new Dictionary<string, ConcurrentTaosQueue>(); 
public bool Open(TaosConnectionStringBuilder builder)
 {
            string connectionString = builder.ConnectionString;
            if (!g_pool.ContainsKey(connectionString))
            {
                g_pool.Add(connectionString, new ConcurrentTaosQueue
                {
                    Timeout = builder.ConnectionTimeout
                });
            }
......
}

**Comment by maikebing** [comment]
抽空提交个PR ?
